# Generated by Django 5.1.4 on 2025-07-12 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_swap_rating',
        ),
        migrations.RemoveConstraint(
            model_name='userachievement',
            name='unique_user_achievement',
        ),
        migrations.RemoveConstraint(
            model_name='userskill',
            name='unique_user_skill_type',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('swap_request', 'rater')},
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill', 'skill_type')},
        ),
    ]
